# Change prefix to Ctrl+a 
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Start pane/session indexing at 1
set -g base-index 1
setw -g pane-base-index 1

# Allow for longer names in the status bar
set -g status-left-length 20

# Simplify the status bar
set -g status-left "[#S] "
set -g status-right "%Y-%m-%d %H:%M"

# Style the bottom bar (transparent background, cyan text)
set -g status-style bg=default,fg=#96cc83

# Intuitive splits
bind H split-window -h \; send-keys "exec bash" Enter "clear" Enter
bind V split-window -v \; send-keys "exec bash" Enter "clear" Enter

# Vim-style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Reload onfig
bind r source-file ~/.tmux.conf \; display "Reloaded!"
