---@diagnostic disable: unused-local
require("luasnip.session.snippet_collection").clear_snippets("markdown")

local ls = require("luasnip")
local s = ls.snippet
local sn = ls.snippet_node
local isn = ls.indent_snippet_node
local t = ls.text_node
local i = ls.insert_node
local f = ls.function_node
local c = ls.choice_node
local d = ls.dynamic_node
local r = ls.restore_node
local events = require("luasnip.util.events")
local ai = require("luasnip.nodes.absolute_indexer")
local extras = require("luasnip.extras")
local l = extras.lambda
local rep = extras.rep
local p = extras.partial
local m = extras.match
local n = extras.nonempty
local dl = extras.dynamic_lambda
local fmt = require("luasnip.extras.fmt").fmt
local fmta = require("luasnip.extras.fmt").fmta
local conds = require("luasnip.extras.expand_conditions")
local postfix = require("luasnip.extras.postfix").postfix
local types = require("luasnip.util.types")
local parse = require("luasnip.util.parser").parse_snippet
local ms = ls.multi_snippet
local k = require("luasnip.nodes.key_indexer").new_key

-- This code checks if we are in math mode by checking for latex_block in the
-- ancestors of the current treesitter node. Inspect the treesitter tree using
-- :InspectTree. This function assumes that the markdown, markdown_inline, and
-- latex treesitter grammars are installed. ignore_injections = false must be
-- passed to vim.treesitter.get_node(), since the latex parser (which creates
-- the inline_formula and displayed_equation treesitter nodes) is injected into
-- the treesitter nodes generated by the markdown and markdown_inline parsers.
local function in_math()
  local node = vim.treesitter.get_node({ignore_injections = false})

  if not node then
    return false
  end

  while node do
    local t = node:type()

    if t == "inline_formula" or t == "displayed_equation" then
      return true
    end

    if t == "text_mode" then
      return false
    end

    node = node:parent()
  end

  return false
end

-- This is a general helper function for creating snippets. Below, I define
-- more concise functions for the three types of snippets: math snippets (_m),
-- regular snippets (_r, expanded with tab), and automatic snippets (_a). 
local function md_snippet(trig, type, str, ins, cond, prio)
	prio = prio or 0
  local nodes = {}
  for idx, val in ipairs(ins) do
    nodes[idx] = i(val, "")
  end

  opts = { trig = trig, snippetType = type, wordTrig = false, priority = prio }
  return s(opts, fmta(str, nodes), cond)
end

local function _m(trig, str, ins, prio)
  return md_snippet(trig, "autosnippet", str, ins, { condition = in_math }, prio)
end

local function _a(trig, str, ins, prio)
  return md_snippet(trig, "autosnippet", str, ins, {}, prio)
end

local function _r(trig, str, ins, prio)
  return md_snippet(trig, "snippet", str, ins, {}, prio)
end

-- Snippet definitions begin here
ls.add_snippets("markdown", {

  -- General snippets
  _r("jira", "[<>](https://jira.tools.sap/browse/<>)", {1, 2}),
  _r("link", "[<>](<>)", {1, 2}),
  _r("table", "| <> | <> |\n|--|--|\n| <> | <> |", {1, 2, 3, 4}),
  _r("icd", "`<>`", {1}),
  _r("dcd", "```\n<>\n```", {1}),

  -- Entering math mode
  _a("mk", "$<>$", {1}),
  _a("dm", "$$\n<>\n$$\n", {1}),

  -- Latex environments
  _m("cases", "\\begin{cases}\n<>\n\\end{cases}", {1}),
  _m("align", "\\begin{aligned}\n<>\n\\end{aligned}", {1}),
  _m("nl", "\\\\[5pt]\n<>", {0}),

  -- Trigonometric Functions
  _m("sin", "\\sin ", {}),
  _m("cos", "\\cos ", {}),
  _m("tan", "\\tan ", {}),
  _m("asin", "\\arcsin ", {}),
  _m("acos", "\\arccos ", {}),
  _m("atan", "\\arctan ", {}),
  _m("hsin", "\\sinh ", {}),
  _m("hcos", "\\cosh ", {}),
  _m("htan", "\\tanh ", {}),

  -- Greek letters
  _m(";a", "\\alpha ", {}),
  _m(";b", "\\beta ", {}),
  _m("chi", "\\chi ", {}),
  _m(";d", "\\delta ", {}),
  _m(";D", "\\Delta ", {}),
  _m(";e", "\\epsilon ", {}),
  _m("eta", "\\eta ", {}),
  _m(";g", "\\gamma ", {}),
  _m(";G", "\\Gamma ", {}),
  _m(";k", "\\kappa ", {}),
  _m(";l", "\\lambda ", {}),
  _m(";L", "\\Lambda ", {}),
  _m("mu", "\\mu ", {}),
  _m("nu", "\\nu ", {}),
  _m(";o", "\\omega ", {}),
  _m(";O", "\\Omega ", {}),
  _m("pi", "\\pi ", {}),
  _m("Pi", "\\Pi ", {}),
  _m("phi", "\\phi ", {}),
  _m("Phi", "\\Phi ", {}),
  _m("vphi", "\\varphi ", {}),
  _m("psi", "\\psi ", {}),
  _m("Psi", "\\Psi ", {}),
  _m("rho", "\\rho ", {}),
  _m(";s", "\\sigma ", {}),
  _m(";S", "\\Sigma ", {}),
  _m("tau", "\\tau ", {}),
  _m(";t", "\\theta ", {}),
  _m(";T", "\\Theta ", {}),
  _m("xi", "\\xi ", {}),
  _m(";z", "\\zeta ", {}),

  -- Brackets, dots, and subscripts
  _m("...", "\\dots ", {}),
  _m("vdot", "\\vdots ", {}),
  _m("ddot", "\\ddots ", {}),
  _m("_", "_{<>}", {1}),
  _m("(", "(<>)", {1}),
  _m("[", "[<>]", {1}),
  _m("abs", "|<>|", {1}),
  _m("set", "\\{<>\\}", {1}),
  _m("ang", "\\langle <> \\rangle ", {1}),
  _m("lr(", "\\left( <> \\right) ", {1}, 1),
  _m("lr[", "\\left[ <> \\right] ", {1}, 1),
  _m("lr|", "\\left| <> \\right| ", {1}, 1),
  _m("lr{", "\\left\\{ <> \\right\\} ", {1}, 1),
  _m("tt", "\\text{<>} ", {1}),

  -- Arithmetic operations
  _m("ff", "\\frac{<>}{<>}", {1, 2}),
  _m("sr", "^2", {}),
  _m("cb", "^3", {}),
  _m("rd", "^{<>}", {1}),
  _m("sq", "\\sqrt{<>}", {1}),
  _m("ee", "e^{<>}", {1}),
  _m("exp", "\\exp", {}),
  _m("oo", "\\infty ", {}),
  _m("neq", "\\neq ", {}),
  _m("geq", "\\geq ", {}),
  _m("leq", "\\leq ", {}),
  _m("ln", "\\ln ", {}),
  _m("log", "\\log ", {}),
  _m("apx", "\\approx ", {}),

  -- Calculus
  _m("sum", "\\sum_{<>}^{<>} ", {1, 2}),
  _m("prd", "\\prod_{<>}^{<>} ", {1, 2}),
  _m("lim", "\\lim_{<>} ", {1}),
  _m("par", "\\frac{\\partial <>}{\\partial <>} ", {1, 2}),
  _m("int", "\\int_{<>}^{<>} <>\\,d", {1, 2, 3}),
  _m("@", "\\Bigg_{<>}^{<>}", {1, 2}),
  _m("max", "\\max ", {}),
  _m("min", "\\min ", {}),

  -- Linear algebra
  _m("odot", "\\dot{<>}", {1}),
  _m("tm", "\\times ", {}),
  _m("dot", "\\cdot ", {}),
  _m("vec", "\\mathbf{<>}", {1}),
  _m("hat", "\\hat{<>}", {1}),
  _m("bar", "\\overline{<>}", {1}),
  _m("tld", "\\tilde{<>}", {1}),
  _m("det", "\\det ", {}),
  _m("trc", "\\text{tr}\\,", {}),
  _m("rk", "\\text{rank}(<>)", {1}),
  _m("aug", "[<>\\,|\\,<>]", {1, 2}),
  _m("nrm", "\\lVert <> \\rVert ", {1}),
  _m("mtx", "\\begin{pmatrix}\n<>\n\\end{pmatrix}", {1}),
  _m("PP", "\\mathbb{P}", {}),

  -- Logic and set theory
  _m("=>", "\\Rightarrow ", {}),
  _m("->", "\\rightarrow ", {}),
  _m("<=>", "\\Leftrightarrow ", {}),
  _m("<->", "\\leftrightarrow ", {}),
  _m("==", "\\equiv ", {}),
  _m("fa", "\\forall ", {}),
  _m("exx", "\\exists ", {}),
  _m("nex", "\\nexists ", {}),
  _m("inn", "\\in ", {}),
  _m("nin", "\\notin ", {}),
  _m("sb", "\\subset ", {}),
  _m("nsb", "\\not\\subset ", {}, 1),
  _m("esb", "\\subseteq ", {}, 1),
  _m("stu", "\\cup ", {}),
  _m("sti", "\\cap ", {}),
  _m("std", "\\setminus ", {}),
  _m("stc", "^{\\complement}", {}),
  _m("bsu", "\\bigcup ", {}),
  _m("bsi", "\\bigcap ", {}),
  _m("qed", "\\blacksquare ", {}),
  _m("#", "\\# ", {}),
  _m("prp", "\\perp ", {}),

  -- Probability
  _m("EE", "\\mathbb{E}", {}),
  _m("chs", "\\binom{<>}{<>}", {1, 2}),
  _m("var", "\\text{Var}\\,", {}),
  _m("cov", "\\text{Cov}\\,", {}),
  _m("eqv", "\\sim ", {}),

  -- Number systems
  _m("CC", "\\mathbb{C}", {}),
  _m("RR", "\\mathbb{R}", {}),
  _m("QQ", "\\mathbb{Q}", {}),
  _m("ZZ", "\\mathbb{Z}", {}),
  _m("NN", "\\mathbb{N}", {}),

  -- Math fonts
  _m("mcl", "\\mathcal{<>}", {1}),
  _m("msf", "\\mathsf{<>}", {1}),
  _m("msr", "\\mathscr{<>}", {1}),

})
