#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Riley Wheadon"
email = "riley.wheadon@sap.com"

[ui]
default-command = "log"

[template-aliases]
'format_short_change_id(id)' = 'id.shortest()'

# use first_ancestors instead of ancestors to hide old merge commits 
[revsets]
log = 'present(@) | first_ancestors(immutable_heads().., 2) | trunk()' 
